### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by thgrund**
Add the SuperDirtMixer repository url.

### CODE REVIEW

**Review by ndr-brt — APPROVED** [review]
I wasn't aware of the SuperDirtMixer, amazing work there!

**Comment by thgrund** [comment]
Hey @ndr-brt and thanks for the appreciation! I just release it two days ago so is kinda brand new. Feel free to use and test it if you like :-)

**Comment by thgrund** [comment]
Oh btw. I can not merge the pull request because of a lack of write permissions.

**Comment by yaxu** [comment]
Thanks !

**Pull request merged**
